language: ruby
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
install:
- gem i matching_bundle
- ruby -e "Dir['gemfiles/*.lock'].each { |f| File.write(f, File.read(f).split('BUNDLED WITH').first) }" # should not be necessary
- matching_bundle install
script: matching_bundle exec rake
branches:
  only: master
gemfile:
 - gemfiles/42.gemfile
 - gemfiles/52.gemfile
 - gemfiles/60.gemfile
matrix:
  exclude:
  - rvm: 2.3
    gemfile: gemfiles/60.gemfile
  - rvm: 2.4
    gemfile: gemfiles/60.gemfile
  - rvm: 2.5
    gemfile: gemfiles/60.gemfile
