language: ruby
bundler_args: ""
sudo: false
rvm:
  - 2.0.0
  - 2.1.5
script: bundle exec rake spec
branches:
  only: master
gemfile:
 - gemfiles/32.gemfile
 - gemfiles/40.gemfile
 - gemfiles/41.gemfile
 - gemfiles/42.gemfile

