language: ruby
bundler_args: ""
sudo: false
rvm:
  - 2.2.4
  - 2.3.1
script: bundle exec rake spec
branches:
  only: master
gemfile:
 - gemfiles/32.gemfile
 - gemfiles/40.gemfile
 - gemfiles/41.gemfile
 - gemfiles/42.gemfile
 - gemfiles/50.gemfile

