language: ruby
sudo: false
rvm:
  - 2.5
  - 2.6
install:
- ruby -e "Dir['gemfiles/*.lock'].each { |f| File.write(f, File.read(f).split('BUNDLED WITH').first) }" # should not be necessary
- bundle install
script: bundle exec rake
branches:
  only: master
gemfile:
 - gemfiles/42.gemfile
 - gemfiles/52.gemfile
 - gemfiles/60.gemfile
matrix:
  exclude:
  - rvm: 2.5
    gemfile: gemfiles/60.gemfile
